### ISSUE TITLE
Download File

### ISSUE THREAD

**Issue by mcselvan** [vneecious/sap-cap-sdm-plugin#14]
Facing issue while downloading file from DMS. In response I am getting the file name but in terminal window getting error like destination undefined. but other functions like create folder, document, delete file, get object are working fine.
<img width="884" alt="image" src="https://github.com/vneecious/sap-cap-sdm-plugin/assets/16464866/fc6879a7-7640-46f0-ab0a-9bde4f596d2f">
<img width="264" alt="image" src="https://github.com/vneecious/sap-cap-sdm-plugin/assets/16464866/2179ad9d-7d1b-4afd-ae6b-2b2dd3857016">

//Repo ID hardcoded in the destination
 response = await client.downloadFile('','M0-CCS-LD1Z8FEsvZ2Px2-INrEnyjhdbBGvx-Wm-45M',{"download" : "attachment", "filename" : "New_Folder.zip", "streamId" : "sap:Rendition"})
      .execute(destination);

**Comment by vneecious** [comment]
Hello @mcselvan , can you check if this PR #24 solves the issue?

**Comment by vneecious** [comment]
For now I'm closing this issue. Please, let me know if the problem persists.
