### ISSUE TITLE
Issue: 409 error when I changed to "Association to many Avatar"

### ISSUE THREAD

**Issue by kaztakata** [vneecious/sap-cap-sdm-plugin#16]
Hi @vneecious,

Thanks for answering to my previous question #15.
Your provided [test/entity-association](https://github.com/vneecious/sap-cap-sdm-plugin/tree/c132a042791b9505f781d06a745ed679642ce9c5/test/crud/entity-association) scenario is perfectly working, so I tried to change to my expecting scenario.

I changed Users entity to `Association to many Avatars` to store multiple files to single User (and relevant folder).
```
entity Users {
    key id     : Int16;
        name   : String;
        avatar : Association to many Avatars
                     on avatar.user = $self;
}
```

I successfully uploaded first file, with changing PUT to POST in `/entity-association/Users(1)/avatar`.
When I tried second file with `POST /entity-association/Users(1)/avatar` again, I got 500 error message `Request failed with status code 409`.
Also I checked console log and found Axios error with below data.
```
data: {
      exception: 'nameConstraintViolation',
      message: 'Child  Users:1 with Id 1760fd7000b121444f5f6b56 already exists'
}
```

I think it is because `onCreate` method is always creating Folder `Users:1` based on navigation. If folder is already there in SDM, we shoud skip folder creation.
I temporarily changed code like below to ignore exception then second upload is successful. 
Do you have better idea to solve above situation? If possible, I would like to support your change.

**Comment by kaztakata** [comment]
Just FYI, below is the updated onCreate method.
```js
/**
 * Handles create operations.
 * @param {Object} req - The request object.
 * @returns {Promise<void>}
 */
const onCreate = async req => {
  const { repositoryId } = getSettings();
  const destination = await loadDestination(req);

  let folderName;
  try {
    folderName = deriveFolderNameFromNavigation(req);
  } catch (e) {
    // nothing to do
  }

  // modified by @kaztakata
  try {
    if (folderName) await onCreateFolder(req, folderName);
  } catch (e) {
    // nothing to do
  }
  //if (folderName) await onCreateFolder(req, folderName);

  const { cmisDocument } = req;
  if (!cmisDocument['cmis:name']) {
    cmisDocument['cmis:name'] = randomUUID();
  }

  const srv = await cds.connect.to('cmis-client');

  const result = await srv
    .createDocument(repositoryId, cmisDocument['cmis:name'], null, {
      folderPath: folderName,
    })
    .execute(destination);
  return convertCMISDocumentToOData(result, req.target.elements);
};
```

**Comment by kaztakata** [comment]
Hi @vneecious, 
I submitted PR #17 for this issue (and one more issue). Could you check?

**Comment by vneecious** [comment]
First, sorry for replying late. Second: thanks a lot for this PR, especially the draft scenarios. Really good! 👍

I'm now closing thie issue.
