### ISSUE TITLE
Error in downloading file content of directory

### ISSUE THREAD

**Issue by kaztakata** [vneecious/sap-cap-sdm-plugin#21]
Hi @vneecious,

After I upgraded `sap-cap-sdm-plugin` [v1.2.5](https://github.com/vneecious/sap-cap-sdm-plugin/commit/260f844c221026e01eda6355fa003923bba314ef), I failed to download file content of directory.
Console log said `%` is used in axios request. It is came from `select * from cmis:folder where cmis:name = '${folderName}'` part of [CMIS query](https://github.com/vneecious/sap-cap-sdm-plugin/blob/master/lib/handlers/index.js#L50-L55) request.
Could you check in your side?

#### part of error log 
```
method: 'get',
    baseURL: 'https://api-sdm-di.cfapps.us10.hana.ondemand.com',
    params: {
      cmisSelector: 'query',
      q: "select%2520*%2520from%2520cmis%253Afolder%2520where%2520cmis%253Aname%2520%253D%2520'CustomerRequests%253A0bdc4ea0-fa7a-42a8-862f-8a44058b36be'",
      _charset: 'UTF-8',
      succinct: 'true',
      searchAllVersions: 'false'
    },
```

**Comment by vneecious** [comment]
I just released a new version v1.2.6 that might fix this. Can you check it out please?

Thanks!

**Comment by kaztakata** [comment]
Hi @vneecious,

Thanks for your quick fix, but my case does not work by v.1.2.6.
Instead, when I change [your code](https://github.com/vneecious/sap-cap-sdm-plugin/blob/ce2f069ba37141880d50b4e9cb41d0747d1054bf/srv/cmis/client.js#L260) to first encode then decode as below, CMIS query is working. 
`      q: decodeURIComponent(encodeURIComponent(statement)),`
Could you check in your side?

**Comment by vneecious** [comment]
Hello @kaztakata, can you check if this PR #24 solves the issue?

**Comment by kaztakata** [comment]
Hi @vneecious,
Thanks for your update. I confirmed no error happened using your branch `21-error-in-downloading-file-content-of-directory`.
