### ISSUE TITLE
File download failed due to TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by kaztakata** [vneecious/sap-cap-sdm-plugin#23]
Hi @vneecious,

After manually resolved CMIS query issue (#21), I hit another error below when I tried download file under folder.
Also, I tried download without navigation folder, but same error below happened.

#### Error message: That error was not happened when I tried v.1.2.4.

```
[cds|be4b8d24-39e3-44f9-8eb8-811dc22eaffa] - TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object
    at new NodeError (node:internal/errors:405:5)
    at readableAddChunk (node:internal/streams/readable:310:13)
    at Readable.push (node:internal/streams/readable:278:10)
    at _ensureStream (/home/kaztakata/projects/sales-agent-ext/code/tenant/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/read.js:507:11)
    at /home/kaztakata/projects/sales-agent-ext/code/tenant/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/read.js:560:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE',
  id: '1066588',
  level: 'ERROR',
  timestamp: 1707977752686
```

Can you successfully download SDM file in your environment?

**Comment by vneecious** [comment]
That's interesting. I think the CAP version installed in your environment is higher than the one I'm using in the library. I just updated its dependency, and the same happened to me. It seems CAP is no longer using `req.query._streaming`, so I have to figure out another way to determine if it's a stream request or not.

I will update `@sap/cds` to `7.6.3` and fix this. I'm thinking that going through the selected columns list and checking if the `content` column is there is the best option; something like this:
```
if (req.query.SELECT.columns.find(c => c.ref.find(r => r == 'content'))) {
   // It's a stream request.
}
```
In theory, this should be enough. I will run some more tests before sending this PR, but for now, I recommend you keep using `v1.2.4`. I will deprecate the two latest versions.

**Comment by vneecious** [comment]
Hello @kaztakata, can you check if this PR #24 solves the issue?

**Comment by kaztakata** [comment]
Hi @vneecious,
Thanks for your update. I confirmed no error happened using your branch `21-error-in-downloading-file-content-of-directory`. Please release this branch as v1.2.7.

I am just curious about your comment and source code change, how do you find `content` from SDM entity? Do you check if property name is `content`? If yes, please share with user to use property name `content`, not `file` etc. I am fine to use `content`.

**Comment by vneecious** [comment]
'content' was just an example. In the final version I've added some logic to find the media property based on the `@Core.MediaType` annotation 😄

Once again, thank you very much for your contribution! 👍

**Comment by kaztakata** [comment]
Hi @vneecious,

> That's interesting. I think the CAP version installed in your environment is higher than the one I'm using in the library. I just updated its dependency, and the same happened to me. It seems CAP is no longer using req.query._streaming, so I have to figure out another way to determine if it's a stream request or not.

It is just FYI, I found latest CAP update relevant to root cause of this issue. [Media Data and Large Binaries](https://cap.cloud.sap/docs/releases/jan24#media-data-and-large-binaries)
