### ISSUE TITLE
Multiple files 

### ISSUE THREAD

**Issue by Sowjanya18127** [vneecious/sap-cap-sdm-plugin#27]
Is this feasible for uploading multiple files !!

Thanks.

**Comment by vneecious** [comment]
By "uploading multiple files," are you referring to sending them all together in a single payload, like using Multipart/Form-data for multiple files? From what I understand, [CAP typically handles files individually](https://cap.cloud.sap/docs/guides/media-data#creating-a-media-resource). I'm not entirely sure if CAP supports multipart uploads in the way you're asking. 

The plugin will soon support ZIP file uploads and direct extraction in SDM, but this is still a [work in progress](https://github.com/vneecious/sap-cap-sdm-plugin/pull/29).
