### ISSUE TITLE
Potential usage of SDM CAP plugin

### ISSUE THREAD

**Issue by ashishjain14** [vneecious/sap-cap-sdm-plugin#8]
Hi Vinicius,

Thanks for developing this plugin. I am just curious to know how do you intend to potentially utilize this plugin? What are the use cases in hand which you intend to solve using this plugin.

Regards,
Ashish

**Comment by vneecious** [comment]
Hello, Ashish. Thank you for your comment. The idea came after I saw the various ways people were implementing integration with SDM from CAP. Typically, folks do it "by hand" using some http client like axios or fetch, and building the form-datas and query params manually. Often, they opt for a more simplified path, utilizing the CmisJS library, [like this example here](https://github.com/gregorwolf/bookshop-demo/blob/main/srv/dms-service.js), but it still requires a significant effort for what I consider to be trivial. That’s why I created the plugin, to enable straightforward integrations, such as attaching files to a specific business process, to be achieved quickly and simply, all through cds annotations and some `cds.requires` settings.

However, the annotations are more suitable for simpler scenarios. For more complex scenarios, where you need more granular control over everything being done or need to implement the more advanced features of CMIS, the annotations might not be very helpful. In such cases, the plugin can still be of use though. It exposes two APIs: `cmis-client` (`cds.connect.to('cmis-client')`), which essentially wraps the CMIS APIs available on the API HUB, and `sdm-admin` (`cds.connect.to('sdm-admin')`), which wraps the Administrative Operations APIs also available on the API HUB.

The first one could be considered a [CmisJS](https://github.com/agea/cmisjs) tailored for SAP BTP, meaning it uses destinations and takes advantage of SAP-specific CMIS functionalities within SDM. It's grounded on the service specifications from the official CMIS 1.1 documentation, with added features that cater to the BTP way of development and enhance the developer's quality of life.

As for the second, honestly, I created it mainly to facilitate the creation and removal of repositories during my integration testing, but if anyone needs it, it’s there 😄

**Comment by vneecious** [comment]
So, answering your questions:

> how do you intend to potentially utilize this plugin?

In any CAP (Node.js) project where i have to implement some kind of integration with SDM service.

> What are the use cases in hand which you intend to solve using this plugin?

The initial use case that started the whole idea is handling processes that may have attachments linked to them. For instance, job candidates attaching resumes, purchase requisitions with multiple attachments, and so on.

**Comment by ashishjain14** [comment]
Hi Vinicius,

Thanks for your quick reply and sharing your thought process! Are there any publicly available samples which consume the SDM CAP plugin? I would love to do a quick hands-on and share feedback on the overall experience.

Regards,
Ashish

**Comment by ashishjain14** [comment]
I see that in the [SAP blog](https://blogs.sap.com/2023/10/02/presenting-sap-cap-sdm-plugin-effortless-integration-between-cap-node.js-and-dms/) you do mention about an [example](https://github.com/vneecious/sap-cap-sdm-plugin/tree/master/example) but looks like the sample is no longer available or may be the link is broken.

**Comment by vneecious** [comment]
i chose to delete [this sample](https://github.com/vneecious/sap-cap-sdm-plugin/tree/12278ddac3741ff0e3831c71fb65bc86a3fb0a64/example/bookshop) because it was too "complex". The plugin was being "hidden" by the large amount of other things there. I'm currently working on an straight-forward sample with a Fiori Elements app embedded to it so it can be more visual and easier to understand, but it will take some time until I finish, because I'm doing it only in my spare time (which has been scarce lately, lol). 
 
meanwhile, if you want to check the plugin in action, you can take a look at the test files. It's not as visual as a working sample, but you can get some insights into what the plugin can do.
