### ISSUE TITLE
501 error 

### ISSUE THREAD

**Issue by Sowjanya18127** [vneecious/sap-cap-sdm-plugin#9]
I tried the blog, but getting 501 "The server does not support the functionality required to fulfill the request" error in CAPM. not sure where i did wrong. i followed the same flow shown in the blog

Thanks

**Comment by vneecious** [comment]
Hmm... It's hard to guess without checking the code, but I suspect that this may be happening because you are not setting the repositoryId in the plugin settings. Since the blog post, I had to make some changes, and one of these was making the repositoryId as required for the bootstrap.

Could you post both your package.json and your repository settings?

**Comment by Sowjanya18127** [comment]
Hey, Thanks for your response..

That issue resolved but still having one
doubt like how to download the documents, also I was able to fetch entire
repository documents but I want only particular document details based on
objectid can you please guide me.

Thanks in advance.

**Comment by vneecious** [comment]
Since it generates a regular OData entity, you can fetch the data likewise.

`/Entity(key)`

**Comment by Sowjanya18127** [comment]
content is not getting fetched in get and download options, in Get call, details are able to fetch except content. 
also while trying to download a document based on object id, entire folder document details without content are downloading.
kindly help me to figure out where it went wrong.

Thanks...

**Comment by vneecious** [comment]
I would suggest you to check [this link](https://cap.cloud.sap/docs/guides/media-data#reading-media-resources).

(Sorry for the delayed response)

**Comment by Sowjanya18127** [comment]
Thanks for the response, i was able to achieve that and finally how to store that table in hana database. even after deployment i was able to see the all the tables except this files entity. can you help here to deploy this table to hana database.

Thanks...🙂

**Comment by vneecious** [comment]
I'm assuming you copied my example. If that's the case, that happens because of the annotation `@cds.persistence.skip`. If you are using the `@Sdm` annotations in your entity, then you don't have to have a table, since all the data is persisted directly in SDM.
